[Backend] Product Api
Milesfeng/order_system pull request #27
Opened 2021-12-29 20:01 UTC by KE-CY

與這支 PR 有關聯的 Otispm卡片:

URL: [Otispm-Project](https://www.otispm.com/otis/index.html#!/pjm/p/8392/todo?sprint=27487&showTodoDetail=131526)

# Description

**Product Api Crud.**
**已合併到 167 測試**
# Step by Step

1. GetAll -> `/api/product `
```json
[
    {
        "id": 1,
        "name": "鹽酥雞",
        "money": 50,
        "image": null,
        "category": 0,
        "status": 0,
        "tags": []
    }
]
```
2. GetByID -> `/api/product/:id`
```json
{
    "id": 1,
    "name": "鹽酥雞",
    "money": 50,
    "image": null,
    "category": 0,
    "status": 0,
    "tags": []
}
```
3.Create -> `/api/product`
body:
```json
{
    "name": "薯條",
    "money": 30,
    "category": 0,
    "status": 0,
    "storeId":1,
    "tags": [1]
}
```
response:
```json
{
    "result": true
}
```
4.Update-> `/api/product/:id`
body:
```json
{
    "storeId": 1,
    "name": "鹽酥雞",
    "money": 500,
    "image": null,
    "category": 0,
    "status": 0,
    "tags": [1]
}
```
response:
```json
{
    "result": true
}
```
5.Delete-> `/api/product/:id`
response:
```json
{
    "result": true
}
```

# Screenshot or more (Optional)

-----------------

提交 PR 前，請先檢查以下是否已完成：

* [x] 該分支是從最新 `master` 切出來 (如果不是，請先 rebase/merge 它)
* [ ] 是否新增測試，或被現有的測試覆蓋
* [x] 這支 PR 是否有明確的標題、內容描述

2021-12-30 08:42 UTC, p0937507934 requested changes

2021-12-30 08:42 UTC, p0937507934 commented on server/docker-compose.yml
> +    security_opt:
can you introduce this tag for us ?
i dont really know what effect it has.

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            console.log("create db error: ", error);
?

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +        if (!name || !money || category === undefined || status === undefined) {
why category === undefined || status === undefined ?

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            tags = tagsData;
tags = tagsData ?

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            console.log("create db error: ", error);
create db error ?

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            return next(new ErrorHandler(errorStatusCode.InternalServerError, errorMsg.InternalServerError));
internal server error ?

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            const newTagId: number[] = <number[]>tags
this block looks weird. product is optional, so if product == undefined or null something, it will causes error ?

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            product.tags = <Tag[]>tagsData;
what is this for

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            console.log("create db error: ", error);
?

2021-12-30 08:42 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            return next(new ErrorHandler(errorStatusCode.InternalServerError, errorMsg.InternalServerError));
same

2021-12-30 10:10 UTC, KE-CY commented on server/docker-compose.yml
> +    security_opt:
在167 up docker compose時有出現下圖的錯誤
![image](https://user-images.githubusercontent.com/54132183/147740797-fbaaf529-6690-4c1c-9a55-06940144964f.png)
後來找到是 docker 的 seccomp 的安全限制問題
所以找到可以先忽視這個安全限制，就是先些改 security_opt 裡的 seccomp:unconfined，因為 docker 預設會帶入seccomp。

2022-01-03 15:35 UTC, p0937507934 commented on server/src/controller/product.controller.ts
> +            tags = tagsData;
那為什麼不傳 tagsData ?

2022-01-03 16:29 UTC, KE-CY commented on server/src/controller/product.controller.ts
> +            tags = tagsData;
因為我 product 的命名是 tags，如果傳 tagsData 在 service assign 會出問題。

2022-01-03 16:55 UTC, aniku777tw commented on server/src/controller/product.controller.ts
> +            product.money = money;
In my opinion, the naming 'price' is better than 'money' .
The meaning will be more clear to understand.

2022-01-03 16:57 UTC, KE-CY commented on server/src/controller/product.controller.ts
> +            product.money = money;
好的 我再做修正

2022-01-05 15:11 UTC, p0937507934 approved these changes

2022-01-05 15:12 UTC, merged